var d=self,l=d.If;(function(){function b(a){e?e.push(a):setTimeout(a,0)}var a={version:"0.7.2.0",Qg:function(a){return void 0===a},Pg:function(a){return null===a},ta:function(a){return null===a||void 0===a},Rg:function(a){return null!==a&&void 0!==a}},e=[];d.attachEvent&&d.attachEvent("onload",function(){if(e){var a=e;e=null;for(var c=0,b=a.length;c<b;c++)a[c]()}});l||(d.If=l={Ta:b,ready:b});for(var c in a)l[c]=a[c]})();Object.la="Object";Object.La=null;Object.wg=function(b){for(var a in b)delete b[a]};
Object.Id=function(b,a){return void 0!==b[a]};Object.keys?Object.yf=function(b){return Object.keys(b).length}:(Object.keys=function(b){var a=[],e;for(e in b)a.push(e);return a},Object.yf=function(b){var a=0,e;for(e in b)a++;return a});Boolean.la="Boolean";Boolean.parse=function(b){return"true"==b.toLowerCase()};Number.la="Number";Number.parse=function(b){return b&&b.length?0<=b.indexOf(".")||0<=b.indexOf("e")||b.endsWith("f")||b.endsWith("F")?parseFloat(b):parseInt(b,10):0};
Number.prototype.format=function(b){return l.ta(b)||0==b.length||"i"==b?this.toString():M(this,b,!1)};Number.prototype.Kd=function(b){return l.ta(b)||0==b.length||"i"==b?this.toLocaleString():M(this,b,!0)};
Number.kc=function(b,a,e,c){var f=null;e=b.indexOf(e);0<e&&(f=b.substr(e),b=b.substr(0,e));(e=b.startsWith("-"))&&(b=b.substr(1));var g=0,h=a[g];if(b.length<h)return f?b+f:b;for(var k=b.length,m="",n=!1;!n;){var p=h,q=k-p;0>q&&(h+=q,p+=q,q=0,n=!0);if(!p)break;q=b.substr(q,p);m=m.length?q+c+m:q;k-=p;g<a.length-1&&(g++,h=a[g])}e&&(m="-"+m);return f?m+f:m};
function M(b,a,e){e=e?l.Qd.Tf.Ef:l.Qd.Uf.Ef;var c="",f=-1;1<a.length&&(f=parseInt(a.substr(1)));a=a.charAt(0);switch(a){case "d":case "D":c=parseInt(Math.abs(b)).toString();-1!=f&&(c=c.length<f?String.Cd(f-c.length)+c:c);0>b&&(c="-"+c);break;case "x":case "X":c=parseInt(Math.abs(b)).toString(16);"X"==a&&(c=c.toUpperCase());-1!=f&&(c=c.length<f?String.Cd(f-c.length)+c:c);break;case "e":case "E":c=-1==f?b.toExponential():b.toExponential(f);"E"==a&&(c=c.toUpperCase());break;case "f":case "F":case "n":case "N":-1==
f&&(f=e.Sg);c=b.toFixed(f).toString();f&&"."!=e.Md&&(f=c.indexOf("."),c=c.substr(0,f)+e.Md+c.substr(f+1));if("n"==a||"N"==a)c=Number.kc(c,e.Ug,e.Md,e.Tg);break;case "c":case "C":-1==f&&(f=e.Ag);c=Math.abs(b).toFixed(f).toString();f&&"."!=e.zd&&(f=c.indexOf("."),c=c.substr(0,f)+e.zd+c.substr(f+1));c=Number.kc(c,e.Cg,e.zd,e.Bg);c=0>b?String.format(e.Dg,c):String.format(e.Eg,c);break;case "p":case "P":-1==f&&(f=e.Vg),c=(100*Math.abs(b)).toFixed(f).toString(),f&&"."!=e.Nd&&(f=c.indexOf("."),c=c.substr(0,
f)+e.Nd+c.substr(f+1)),c=Number.kc(c,e.Xg,e.Nd,e.Wg),c=0>b?String.format(e.Yg,c):String.format(e.Zg,c)}return c}String.la="String";String.Rd="";String.compare=function(b,a,e){e&&(b&&(b=b.toUpperCase()),a&&(a=a.toUpperCase()));b=b||"";a=a||"";return b==a?0:b<a?-1:1};String.concat=function(){return 2===arguments.length?arguments[0]+arguments[1]:Array.prototype.join.call(arguments,"")};
String.prototype.endsWith=function(b){return b.length?b.length>this.length?!1:this.substr(this.length-b.length)==b:!0};String.Ga=function(b,a,e){return 0==String.compare(b,a,e)};String.ad=function(b,a,e){String.bd||(String.bd=/(\{[^\}^\{]+\})/g);return b.replace(String.bd,function(c,b){var g=a[parseInt(b.substr(1))+1];if(l.ta(g))return"";if(g.format){var h=null,k=b.indexOf(":");0<k&&(h=b.substring(k+1,b.length-1));return e?g.Kd(h):g.format(h)}return e?g.toLocaleString():g.toString()})};
String.format=function(b){return String.ad(b,arguments,!1)};String.Cd=function(b){for(var a="0",e=1;e<b;e++)a+="0";return a};String.prototype.insert=function(b,a){return a?b?this.substr(0,b)+a+this.substr(b):a+this:this};String.Hd=function(b){return!b||!b.length};String.Kd=function(b){return String.ad(b,arguments,!0)};String.prototype.remove=function(b,a){return!a||b+a>this.length?this.substr(0,b):this.substr(0,b)+this.substr(b+a)};
String.prototype.startsWith=function(b){return b.length?b.length>this.length?!1:this.substr(0,b.length)==b:!0};String.prototype.trim||(String.prototype.trim=function(){return this.replace(/\s*$/,"").replace(/^\s*/,"")});Array.la="Array";Array.Kb=[l.Hb];
Object.defineProperties(Array.prototype,{add:{value:function(b){this.push(b)}},addRange:{value:function(b){this.push.apply(this,b)}},aggregate:{value:function(b,a,e){for(var c=this.length,f=0;f<c;f++)f in this&&(b=a.call(e,b,this[f],f,this));return b}},clear:{value:function(){this.length=0}},clone:{value:function(){return 1===this.length?[this[0]]:Array.apply(null,this)}},contains:{value:function(b){return 0<=this.indexOf(b)}},dequeue:{value:function(){return this.shift()}},enqueue:{value:function(b){this.lf=
!0;this.push(b)}},peek:{value:function(){return this.length?this[this.lf?0:this.length-1]:null}},extract:{value:function(b,a){return a?this.slice(b,b+a):this.slice(b)}},getEnumerator:{value:function(){return new l.Fb(this)}},groupBy:{value:function(b,a){for(var e=this.length,c=[],f={},g=0;g<e;g++)if(g in this){var h=b.call(a,this[g],g);if(!String.Hd(h)){var k=f[h];k||(k=[],k.key=h,f[h]=k,c.add(k));k.add(this[g])}}return c}},index:{value:function(b,a){for(var e=this.length,c={},f=0;f<e;f++)if(f in
this){var g=b.call(a,this[f],f);String.Hd(g)||(c[g]=this[f])}return c}},insert:{value:function(b,a){this.splice(b,0,a)}},insertRange:{value:function(b,a){if(0===b)this.unshift.apply(this,a);else for(var e=0;e<a.length;e++)this.splice(b+e,0,a[e])}},remove:{value:function(b){b=this.indexOf(b);return 0<=b?(this.splice(b,1),!0):!1}},removeAt:{value:function(b){this.splice(b,1)}},removeRange:{value:function(b,a){return this.splice(b,a)}}});
Array.prototype.every||Object.defineProperty(Array.prototype,"every",{value:function(b,a){for(var e=this.length,c=0;c<e;c++)if(c in this&&!b.call(a,this[c],c,this))return!1;return!0}});Array.prototype.filter||Object.defineProperty(Array.prototype,"filter",{value:function(b,a){for(var e=this.length,c=[],f=0;f<e;f++)if(f in this){var g=this[f];b.call(a,g,f,this)&&c.push(g)}return c}});
Array.prototype.forEach||Object.defineProperty(Array.prototype,"forEach",{value:function(b,a){for(var e=this.length,c=0;c<e;c++)c in this&&b.call(a,this[c],c,this)}});Array.prototype.indexOf||Object.defineProperty(Array.prototype,"indexOf",{value:function(b,a){var e=this.length;if(e)for(var c=a||0;c<e;c++)if(this[c]===b)return c;return-1}});
Array.prototype.map||Object.defineProperty(Array.prototype,"map",{value:function(b,a){for(var e=this.length,c=Array(e),f=0;f<e;f++)f in this&&(c[f]=b.call(a,this[f],f,this));return c}});Array.parse=function(b){return eval("("+b+")")};Array.prototype.some||Object.defineProperty(Array.prototype,"some",{value:function(b,a){for(var e=this.length,c=0;c<e;c++)if(c in this&&b.call(a,this[c],c,this))return!0;return!1}});Array.Kf=function(b){return Array.prototype.slice.call(b)};RegExp.la="RegExp";
RegExp.parse=function(b){if(b.startsWith("/")){var a=b.lastIndexOf("/");if(1<a)return new RegExp(b.substring(1,a),b.substr(a+1))}return null};Error.la="Error";
Error.yg=function(b,a,e){b=Error(b);if(a)for(var c in a)b[c]=a[c];e&&(b.Ig=e);if(!(l.ta(b.stack)||l.ta(b.fileName)||l.ta(b.lineNumber))){a=b.stack.split("\n");e=a[0];for(c=b.fileName+":"+b.lineNumber;!l.ta(e)&&-1===e.indexOf(c);)a.shift(),e=a[0];e=a[1];isNullOrUndefined(e)||(e=e.match(/@(.*):(\d+)$/),l.ta(e)||(a.shift(),b.stack=a.join("\n"),b.fileName=e[1],b.lineNumber=parseInt(e[2])))}return b};l.va=d.va||function(){};l.va.la="Debug";
l.va.writeln||(l.va.writeln=function(b){d.console?d.console.debug?d.console.debug(b):d.console.log&&d.console.log(b):d.opera&&d.opera.postError&&d.opera.postError(b)});l.va.$c=function(b){l.va.writeln(b);eval("debugger;")};l.va.assert=function(b,a){b||(a="Assert failed: "+a,confirm(a+"\r\n\r\nBreak into debugger?")&&l.va.$c(a))};l.va.Gg=function(b){l.va.$c(b)};d.J=Function;d.J.la="Type";d.Nc=function(b){this.la=b};d.Nc.prototype={be:!0,getName:function(){return this.la}};
d.J.Ff=function(){d.ic||(d.ic={});d.Rc||(d.Rc=[]);if(!d.ic.trn){for(var b=self,a=["trn"],e=0;e<a.length;e++){var c=a[e],f=b[c];f||(b[c]=f=new d.Nc(a.slice(0,e+1).join(".")),0==e&&d.Rc.add(f));b=f}d.ic.trn=b}};d.J.prototype.$=function(b,a,e){this.prototype.constructor=this;this.la=b;this.Oc=!0;this.La=a||Object;a&&(this.Jb=!0);if(e){this.Kb=[];for(var c=2;c<arguments.length;c++)e=arguments[c],this.Kb.add(e)}};function Q(b,a){b.la=a;b.Qc=!0}
d.J.prototype.Ec=function(){if(this.Jb){var b=this.La;b.Jb&&b.Ec();for(var a in b.prototype){var e=b.prototype[a];this.prototype[a]||(this.prototype[a]=e)}delete this.Jb}};d.J.prototype.Gf||(d.J.prototype.Gf=d.J.prototype.Ec);function R(b,a){return l.ta(a)?!1:b==Object||a instanceof b?!0:S(b,d.J.xf(a))}
function S(b,a){if(b==Object||b==a)return!0;if(b.Oc)for(var e=a.La;e;){if(b==e)return!0;e=e.La}else if(b.Qc){var c=a.Kb;if(c&&c.contains(b))return!0;for(e=a.La;e;){if((c=e.Kb)&&c.contains(b))return!0;e=e.La}}return!1}d.J.Kg=function(b){return 1==b.Oc};d.J.Lg=function(b){return 1==b.ae};d.J.Mg=function(b){return 1==b.ae&&1==b.Pc};d.J.Ng=function(b){return 1==b.Qc};d.J.Og=function(b){return 1==b.be};d.J.ug=function(b,a){return R(a,b)};d.J.ah=function(b,a){return R(a,b)?b:null};
d.J.xf=function(b){var a=null;try{a=b.constructor}catch(e){}a&&a.la||(a=Object);return a};d.J.Af=function(b){if(!b)return null;d.J.jc||(d.J.jc={});var a=d.J.jc[b];a||(a=eval(b),d.J.jc[b]=a);return a};d.J.parse=function(b){return d.J.Af(b)};l.gc=function(){};l.gc.$("Enum");
l.gc.parse=function(b,a){var e=b.prototype;if(b.Pc){for(var c=a.split("|"),f=0,g=!0,h=c.length-1;0<=h;h--){var k=c[h].trim(),m=!1;for(n in e)if(n===k){f|=e[n];m=!0;break}if(!m){g=!1;break}}if(g)return f}else for(var n in e)if(n===a)return e[n];throw"Invalid Enumeration Value";};
l.gc.cg=function(b){var a=this.prototype;if(this.Pc&&0!==b){var e=[];for(c in a)a[c]&b&&(e.length&&e.add(" | "),e.add(c));if(!e.length)throw"Invalid Enumeration Value";return e.join("")}for(var c in a)if(a[c]===b)return c;throw"Invalid Enumeration Value";};l.X=function(){};l.X.$("Delegate");l.X.empty=function(){};l.X.ge=function(b,a,e){for(var c=0;c<b.length;c+=2)if(b[c]===a&&b[c+1]===e)return!0;return!1};
l.X.lc=function(b){function a(){if(2==b.length)return b[1].apply(b[0],arguments);for(var a=b.clone(),c=0;c<a.length;c+=2)l.X.ge(b,a[c],a[c+1])&&a[c+1].apply(a[c],arguments);return null}a.xa=b;return a};l.X.create=function(b,a){return b?l.X.lc([b,a]):a};l.X.xg=function(b,a){return b?a?l.X.lc((b.xa?b.xa:[null,b]).concat(a.xa?a.xa:[null,a])):b.xa?b:l.X.create(null,b):a.xa?a:l.X.create(null,a)};
l.X.remove=function(b,a){if(!b||b===a)return null;if(!a)return b;var e=b.xa,c=null,f;a.xa?(c=a.xa[0],f=a.xa[1]):f=a;for(var g=0;g<e.length;g+=2)if(e[g]===c&&e[g+1]===f){if(2==e.length)return null;e.splice(g,2);return l.X.lc(e)}return b};l.X.zg=function(b,a,e){e=e||"__"+(new Date).valueOf();self[e]=a?b:function(){try{delete self[e]}catch(a){self[e]=void 0}b.apply(null,arguments)};return e};l.X.Fg=function(b){delete self[b]};l.X.vg=function(b){self[b]=l.X.empty};l.ob=function(){};
l.ob.prototype={Ld:null,reset:null};l.ob.getEnumerator=function(b){return b?b.getEnumerator?b.getEnumerator():new l.Fb(b):null};Q(l.ob,"IEnumerator");l.Hb=function(){};l.Hb.prototype={getEnumerator:null};Q(l.Hb,"IEnumerable");l.Fb=function(b){this.Sc=b;this.Da=-1;this.current=null};l.Fb.prototype={Ld:function(){this.Da++;this.current=this.Sc[this.Da];return this.Da<this.Sc.length},reset:function(){this.Da=-1;this.current=null}};l.Fb.$("ArrayEnumerator",null,l.ob);l.Jc=function(){};
l.Jc.prototype={uf:null};Q(l.Jc,"IDisposable");l.Lc=function(b){this.Ac=l.ta(b)?[]:[b]};l.Lc.prototype={append:function(b){l.ta(b)||this.Ac.add(b);return this},clear:function(){this.Ac=[]},toString:function(b){return this.Ac.join(b||"")}};l.Lc.$("StringBuilder");l.Gb=function(){};l.Gb.$("EventArgs");l.Gb.Rd=new l.Gb;d.XMLHttpRequest||(d.XMLHttpRequest=function(){for(var b=["Msxml2.XMLHTTP","Microsoft.XMLHTTP"],a=0;a<b.length;a++)try{return new ActiveXObject(b[a])}catch(e){}return null});
l.Ic=function(){var b=l.Ic;b.Jb&&b.Ec();b.La.apply(this);this.cancel=!1};l.Ic.$("CancelEventArgs",l.Gb);l.Zd=function(b,a){this.first=b;this.second=a};l.Zd.$("Tuple");l.ka=function(){this.zb=null};l.ka.prototype={};l.ka.zc=[];l.ka.ef={uf:function(){l.ka.zc.pop()}};l.ka.$g=function(b){l.ka.zc.push(b);return l.ka.ef};l.ka.ee=function(b){var a=l.ka.zc,e=a.length;if(e){b=b||[];for(var c=0;c<e;c++){var f=a[c];b.contains(f)||b.push(f)}return b}return null};l.ka.Xe=function(b){for(var a=0,e=b.length;a<e;a++)b[a].Jg()};
l.ka.$("Observable");l.Kc=function(b){this.za=b||[];this.zb=null};
l.Kc.prototype={add:function(b){this.za.push(b);T(this)},clear:function(){this.za.clear();T(this)},contains:function(b){return this.za.contains(b)},getEnumerator:function(){this.zb=l.ka.ee(this.zb);return this.za.getEnumerator()},indexOf:function(b){return this.za.indexOf(b)},insert:function(b,a){this.za.insert(b,a);T(this)},remove:function(b){return this.za.remove(b)?(T(this),!0):!1},removeAt:function(b){this.za.removeAt(b);T(this)},Kf:function(){return this.za}};
function T(b){var a=b.zb;a&&(b.zb=null,l.ka.Xe(a))}l.Kc.$("ObservableCollection",null,l.Hb);l.Sd=function(){};Q(l.Sd,"IApplication");l.Td=function(){};Q(l.Td,"IContainer");l.Wd=function(){};Q(l.Wd,"IObjectFactory");l.Ud=function(){};Q(l.Ud,"IEventManager");l.Vd=function(){};Q(l.Vd,"IInitializable");(function(b){function a(a,b,f,g,h,k){this.Ka=16;this.Yd=288;this.status=0;this.root=null;this.Aa=0;var m=Array(this.Ka+1),n,z,y,v,t,u,I,J=Array(this.Ka+1),G,F,C,B=new e,N=Array(this.Ka);v=Array(this.Yd);var D,K=Array(this.Ka+1),O,L,P;P=this.root=null;for(t=0;t<m.length;t++)m[t]=0;for(t=0;t<J.length;t++)J[t]=0;for(t=0;t<N.length;t++)N[t]=null;for(t=0;t<v.length;t++)v[t]=0;for(t=0;t<K.length;t++)K[t]=0;n=256<b?a[256]:this.Ka;G=a;F=0;t=b;do m[G[F]]++,F++;while(0<--t);if(m[0]==b)this.root=null,this.status=
this.Aa=0;else{for(u=1;u<=this.Ka&&0==m[u];u++);I=u;k<u&&(k=u);for(t=this.Ka;0!=t&&0==m[t];t--);y=t;k>t&&(k=t);for(O=1<<u;u<t;u++,O<<=1)if(0>(O-=m[u])){this.status=2;this.Aa=k;return}if(0>(O-=m[t]))this.status=2,this.Aa=k;else{m[t]+=O;K[1]=u=0;G=m;F=1;for(C=2;0<--t;)K[C++]=u+=G[F++];G=a;t=F=0;do 0!=(u=G[F++])&&(v[K[u]++]=t);while(++t<b);b=K[y];K[0]=t=0;G=v;F=0;v=-1;D=J[0]=0;C=null;for(L=0;I<=y;I++)for(a=m[I];0<a--;){for(;I>D+J[1+v];){D+=J[1+v];v++;L=(L=y-D)>k?k:L;if((z=1<<(u=I-D))>a+1)for(z-=a+1,
C=I;++u<L&&!((z<<=1)<=m[++C]);)z-=m[C];D+u>n&&D<n&&(u=n-D);L=1<<u;J[1+v]=u;C=Array(L);for(z=0;z<L;z++)C[z]=new e;P=null==P?this.root=new c:P.next=new c;P.next=null;P.list=C;N[v]=C;0<v&&(K[v]=t,B.sa=J[v],B.e=16+u,B.t=C,u=(t&(1<<D)-1)>>D-J[v],N[v-1][u].e=B.e,N[v-1][u].sa=B.sa,N[v-1][u].n=B.n,N[v-1][u].t=B.t)}B.sa=I-D;F>=b?B.e=99:G[F]<f?(B.e=256>G[F]?16:15,B.n=G[F++]):(B.e=h[G[F]-f],B.n=g[G[F++]-f]);z=1<<I-D;for(u=t>>D;u<L;u+=z)C[u].e=B.e,C[u].sa=B.sa,C[u].n=B.n,C[u].t=B.t;for(u=1<<I-1;0!=(t&u);u>>=
1)t^=u;for(t^=u;(t&(1<<D)-1)!=K[v];)D-=J[v],v--}this.Aa=J[1];this.status=0!=O&&1!=y?1:0}}}function e(){this.n=this.sa=this.e=0;this.t=null}function c(){this.list=this.next=null}var f=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],g=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],h=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,99,99],k=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,
6145,8193,12289,16385,24577],m=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],n=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];b.Xa||(b.Xa={});b.Xa.hc=function(a){this.Rf();this.ec=a;this.fc=0};b.Xa.hc.prototype={Dd:function(a){for(var c,e=Array(1024),b=[],f=0;f<a&&0<(c=this.Qf(e,0,e.length));)b[b.length]=String.fromCharCode.apply(null,e.slice(0,c)),f+=c;return f?(this.ec=this.ec.slice(this.fc),this.fc=0,b.join("")):""},Mf:function(){return this.ec.length==this.fc?-1:this.ec.charCodeAt(this.fc++)&
255},O:function(a){for(;this.Ua<a;)this.nb|=this.Mf()<<this.Ua,this.Ua+=8},S:function(a){return this.nb&f[a]},N:function(a){this.nb>>=a;this.Ua-=a},dc:function(a,c,e){var b,f,g;if(0==e)return 0;for(g=0;;){this.O(this.ua);f=this.Ja.list[this.S(this.ua)];for(b=f.e;16<b;){if(99==b)return-1;this.N(f.sa);b-=16;this.O(b);f=f.t[this.S(b)];b=f.e}this.N(f.sa);if(16==b)this.da&=32767,a[c+g++]=this.Ia[this.da++]=f.n;else{if(15==b)break;this.O(b);this.ja=f.n+this.S(b);this.N(b);this.O(this.mb);f=this.Pd.list[this.S(this.mb)];
for(b=f.e;16<b;){if(99==b)return-1;this.N(f.sa);b-=16;this.O(b);f=f.t[this.S(b)];b=f.e}this.N(f.sa);this.O(b);this.Va=this.da-f.n-this.S(b);for(this.N(b);0<this.ja&&g<e;)this.ja--,this.Va&=32767,this.da&=32767,a[c+g++]=this.Ia[this.da++]=this.Ia[this.Va++]}if(g==e)return e}this.Ha=-1;return g},Sf:function(a,c,e){var b;b=this.Ua&7;this.N(b);this.O(16);b=this.S(16);this.N(16);this.O(16);if(b!=(~this.nb&65535))return-1;this.N(16);this.ja=b;for(b=0;0<this.ja&&b<e;)this.ja--,this.da&=32767,this.O(8),a[c+
b++]=this.Ia[this.da++]=this.S(8),this.N(8);0==this.ja&&(this.Ha=-1);return b},Pf:function(c,e,b){if(null==this.cc){var f,n=Array(288);for(f=0;144>f;f++)n[f]=8;for(;256>f;f++)n[f]=9;for(;280>f;f++)n[f]=7;for(;288>f;f++)n[f]=8;this.Hc=7;f=new a(n,288,257,g,h,this.Hc);if(0!=f.status)return alert("HufBuild error: "+f.status),-1;this.cc=f.root;this.Hc=f.Aa;for(f=0;30>f;f++)n[f]=5;this.Gc=5;f=new a(n,30,0,k,m,this.Gc);if(1<f.status)return this.cc=null,alert("HufBuild error: "+f.status),-1;this.Nf=f.root;
this.Gc=f.Aa}this.Ja=this.cc;this.Pd=this.Nf;this.ua=this.Hc;this.mb=this.Gc;return this.dc(c,e,b)},Of:function(c,e,b){var f,r,A,H,E,z,y,v=Array(316);for(f=0;f<v.length;f++)v[f]=0;this.O(5);z=257+this.S(5);this.N(5);this.O(5);y=1+this.S(5);this.N(5);this.O(4);f=4+this.S(4);this.N(4);if(286<z||30<y)return-1;for(r=0;r<f;r++)this.O(3),v[n[r]]=this.S(3),this.N(3);for(;19>r;r++)v[n[r]]=0;this.ua=7;r=new a(v,19,19,null,null,this.ua);if(0!=r.status)return-1;this.Ja=r.root;this.ua=r.Aa;H=z+y;for(f=A=0;f<
H;)if(this.O(this.ua),E=this.Ja.list[this.S(this.ua)],r=E.sa,this.N(r),r=E.n,16>r)v[f++]=A=r;else if(16==r){this.O(2);r=3+this.S(2);this.N(2);if(f+r>H)return-1;for(;0<r--;)v[f++]=A}else{17==r?(this.O(3),r=3+this.S(3),this.N(3)):(this.O(7),r=11+this.S(7),this.N(7));if(f+r>H)return-1;for(;0<r--;)v[f++]=0;A=0}this.ua=9;r=new a(v,z,257,g,h,this.ua);0==this.ua&&(r.status=1);if(0!=r.status)return-1;this.Ja=r.root;this.ua=r.Aa;for(f=0;f<y;f++)v[f]=v[f+z];this.mb=6;r=new a(v,y,0,k,m,this.mb);this.Pd=r.root;
this.mb=r.Aa;return 0==this.mb&&257<z||0!=r.status?-1:this.dc(c,e,b)},Rf:function(){null==this.Ia&&(this.Ia=Array(65536));this.Ua=this.nb=this.da=0;this.Ha=-1;this.bc=!1;this.ja=this.Va=0;this.cc=this.Ja=null},Qf:function(a,c,e){var b,f;for(b=0;b<e&&(!this.bc||-1!=this.Ha);){if(0<this.ja){if(0!=this.Ha)for(;0<this.ja&&b<e;)this.ja--,this.Va&=32767,this.da&=32767,a[c+b++]=this.Ia[this.da++]=this.Ia[this.Va++];else{for(;0<this.ja&&b<e;)this.ja--,this.da&=32767,this.O(8),a[c+b++]=this.Ia[this.da++]=
this.S(8),this.N(8);0==this.ja&&(this.Ha=-1)}if(b==e)break}if(-1==this.Ha){if(this.bc)break;this.O(1);0!=this.S(1)&&(this.bc=!0);this.N(1);this.O(2);this.Ha=this.S(2);this.N(2);this.Ja=null;this.ja=0}switch(this.Ha){case 0:f=this.Sf(a,c+b,e-b);break;case 1:f=null!=this.Ja?this.dc(a,c+b,e-b):this.Pf(a,c+b,e-b);break;case 2:f=null!=this.Ja?this.dc(a,c+b,e-b):this.Of(a,c+b,e-b);break;default:f=-1}if(-1==f)return this.bc?0:-1;b+=f}return b}};b.Xa.Gd=function(a){return(new b.Xa.hc(a)).Dd(4E9)}})(self);(function(b){function a(a){this.depth=this.index=0;this.I=a;this.location={start:0,Zb:1,$b:1,end:a.length,empty:!0};this.Cb=[this.location];this.Dc=!1;"?"===this.I.charAt(1)&&this.Fd();this.location.empty=!1}b.Ib=b.Ib?b.Ib:{};b.Ib.Lf=function(a){if(a)return a.replace(/&[^;]*;/g,function(a){switch(a.charAt(1)){case "q":return'"';case "a":return"&";case "l":return"<";case "g":return">";case "#":return"x"===a.charAt(2)?String.fromCharCode(parseInt(a.substring(3,a.length-1),16)):String.fromCharCode(parseInt(a.substring(2,
a.length-1),10))}return a})};a.prototype={advance:function(){this.Fa=null;this.Fd();var a=this.location.start;++a;this.location.empty=!1;if("/"!==this.I.charAt(a))return this.location.empty="/"===this.I.charAt(this.I.indexOf(">",a)-1),!0;this.location.end=!0;return!1},Jd:function(){var a=this.location.start+1,c=this.I.indexOf(">",a);this.location.empty&&--c;a=this.I.substring(a,c);this.Fa={};c=a.indexOf(" ");if(-1!==c){this.Bd=a.substring(0,c);for(var a=a.slice(c),a=a.split('"'),c=a.length-1,b=0;b<
c;++b){var g=a[b],h=a[++b];this.Fa[g.substring(1,g.length-1)]=h}}else this.Bd=a},Fd:function(){if(this.Dc)this.Dc=!1,this.location.start=this.I.indexOf("<",this.location.start+1);else{var a=this.location.Zb;if(!this.location.empty)for(var c=this.location.$b;0<c;)a=this.I.indexOf("<",a),"/"===this.I.charAt(++a)?--c:(a=this.I.indexOf(">",a),"/"!==this.I.charAt(a-1)&&++c);this.location.start=this.I.indexOf("<",a)}this.location.Zb=this.location.start+1;this.location.$b=1},mark:function(){this.I.mark&&
this.I.mark(this.location.start)},L:function(){null!==this.Fa&&"undefined"!==typeof this.Fa||this.Jd();return this.Bd},F:function(){++this.depth;this.location={start:this.location.start};this.Cb[this.Cb.length]=this.location;this.Dc=!0},C:function(){--this.depth;this.Fa=null;var a=this.location.Zb,c=this.location.$b,b=this.location.empty,g=this.location.end;this.Cb.pop();this.location=this.Cb[this.Cb.length-1];this.location.Zb=a;this.location.$b=g?0:b?c:c+1},R:function(){return this.location.empty?
!0:"/"===this.I.charAt(this.I.indexOf("<",this.location.start+1)+1)},D:function(a){null!==this.Fa&&"undefined"!==typeof this.Fa||this.Jd();return b.Ib.Lf(this.Fa[a])}};b.$d=a})(self);(function(){function b(a,e){this.m=[];this.o=[];a&&this.H(a,e)}self.J.Ff();String.fromCodePoint||function(){function a(){var a=[],e,k,m=-1,n=arguments.length;if(!n)return"";for(var p="";++m<n;){k=Number(arguments[m]);if(!isFinite(k)||0>k||1114111<k||b(k)!==k)throw RangeError("Invalid code point: "+k);65535>=k?a.push(k):(k-=65536,e=(k>>10)+55296,k=k%1024+56320,a.push(e,k));if(m+1===n||16384<a.length)p+=c.apply(null,a),a.length=0}return p}var e=function(){var a;try{var c={},e=Object.defineProperty;
a=e(c,c,c)&&e}catch(b){}return a}(),c=String.fromCharCode,b=Math.floor;e?e(String,"fromCodePoint",{value:a,configurable:!0,writable:!0}):String.fromCodePoint=a}();Array.prototype.Ga&&console.warn("Overriding existing Array.prototype.equals. Possible causes: New API defines the method, there's a framework conflict or you've got double inclusions in your code.");Array.prototype.Ga=function(a){if(!a||this.length!==a.length)return!1;for(var e=0,c=this.length;e<c;e++)if(this[e]instanceof Array&&a[e]instanceof
Array){if(!this[e].Ga(a[e]))return!1}else if(this[e]!==a[e])return!1;return!0};Object.defineProperty(Array.prototype,"equals",{enumerable:!1});b.prototype={B:function(a){this.m=this.m.concat(a.m);this.o=this.o.concat(a.o)},H:function(a,e){this.m.push(a);var c=typeof e;this.o.push("object"===c?e:"undefined"===c?null:[e])},Ga:function(a){return this.m.Ga(a.m)&&this.o.Ga(a.o)},save:function(){this.m.push(d.trn.a.Ge);this.o.push(null)},restore:function(){this.H(d.trn.a.Fe,null)},Od:function(a){this.m.push(d.trn.a.qb);
this.o.push(a.rb())}};d.trn.a=function(a,e,c){this.done=!1;this.hd=2E3;this.Qa={};this.Sa=this.bf=0;this.M=[];this.Rb=[];this.ga=[];this.ga.add({});this.vc=0;this.b=a;this.md=this.Eb("Width");this.ld=this.Eb("Height");this.M.push(d.trn.Na.Bf(this.md,this.ld));this.fa=!1;this.gd=e;this.Qb=c;this.Ye=-1<navigator.userAgent.indexOf("Android")&&-1===navigator.userAgent.indexOf("Chrome")&&-1===navigator.userAgent.indexOf("Firefox");this.m=[];this.o=[];this.b.F();this.b.advance();a=this.b.L();d.trn.a.g(a,
"FixedPage.Resources")&&(this.b.F(),this.b.advance(),this.sd(),this.b.C());this.Pa=!1};d.trn.a.g=function(a,e){var c=d.trn.a.tf;return a===e?!0:a===c+e};d.trn.a.Ad=function(a){return d.trn.a.vf(a)};d.trn.a.vf=function(a){var e=3,c=Math.abs(a);.5>c&&(e=5E-4>c?5E-7>c?9:7:5);e=Math.pow(10,e);a=Math.round(a*e)/e;return a.toString()};d.trn.a.A=function(a,e){if(!a)throw Error(e);};d.trn.a.Hg=function(a){return(new d.trn.a(a,!1)).Me()};d.trn.a.prototype={Ue:function(){return this.qc()},mc:function(a,e){var c,
b=this.Le(),g=this.b.L();d.trn.a.g(g,"Path")?c=this.oc():d.trn.a.g(g,"Canvas")?c=this.Ob():d.trn.a.g(g,"Glyphs")?c=this.nc():(c=null,d.trn.a.A(!1,"Invalid Element "+g));c.lb(b);if(c.Cf()){b=this.Ue();g=this.$a();b.mtx=[g.T,g.U,g.V,g.W,g.ba,g.ca];if(a){a={operators:a.m,data:a.o};var h=this.b.D("RenderTransform");if(null!=h){var k=new d.trn.G;k.aa(h);h=new d.trn.G;h.rc(g);h.Ma(k);g=h}a.mtx=[g.T,g.U,g.V,g.W,g.ba,g.ca]}this.H(d.trn.a.Je,[b,{x1:c.j,y1:c.l,x2:c.j+c.v,y2:c.l+c.u},e,a]);this.nd=!0}else this.fa=
!1},Ob:function(){var a=new d.trn.ea;this.Z();var e=this.b.D("RenderTransform");if(null!=e){var c=new d.trn.G;c.aa(e);this.Y(c)}e=this.b.D("Clip");null!=e&&(a=this.Ca(e));e=null;if(!this.b.R()){for(this.b.F();this.b.advance();)c=this.b.L(),d.trn.a.g(c,"Canvas.Clip")?(d.trn.a.A(!this.b.R(),"Canvas.Clip: Must contain PathGeometry element"),this.b.F(),this.b.advance()&&(c=new d.trn.G,c.aa(this.s("Transform")),this.Y(c),a.lb(this.Ca(this.s("Figures"))),c=c.tb(),this.Y(c)),this.b.C()):d.trn.a.g(c,"Path")?
null!=e?e.Fc(this.oc()):e=this.oc():d.trn.a.g(c,"Glyphs")?null!=e?e.Fc(this.nc()):e=this.nc():d.trn.a.g(c,"Canvas")&&(null!=e?e.Fc(this.Ob()):e=this.Ob());this.b.C()}null!=e&&a.lb(e);this.pa();return a},gf:function(){var a=this.Ba("trn:BlendMode","source-over"),a=this.fa?"source-over":a,e=this.Bc();e||(this.save(),this.Z());var c=null,f=this.b.D("OpacityMask");null!=f&&(console.warn("Uh oh OpacityMask Resource!"),c=this.Oa(f));if(!this.b.R()){for(this.b.F();this.b.advance();)if(f=this.b.L(),d.trn.a.g(f,
"Canvas.Resources"))this.b.R()?d.trn.a.A(!1,"Canvas.Resources must contain ResourceDictionary element"):(this.b.F(),this.b.advance(),this.sd(),this.b.C());else if(d.trn.a.g(f,"Canvas.Clip"))d.trn.a.A(!this.b.R(),"Canvas.Clip: Must contain PathGeometry element"),this.b.F(),this.b.advance()&&(e||(this.save(),e=!0,this.Z()),f=new d.trn.G,f.aa(this.s("Transform")),this.B(this.Y(f)),d.trn.a.A(d.trn.a.g(this.b.L(),"PathGeometry"),"Path.Clip must contain PathGeometry"),this.Yb(this.s("Figures")),f=f.tb(),
this.B(this.Y(f))),this.b.C();else if(d.trn.a.g(f,"Canvas.OpacityMask"))this.fa||(this.b.F(),this.b.advance(),c=this.Za(d.trn.a.ma,new b(d.trn.a.Mb)),this.b.C());else if(d.trn.a.g(f,"Path")||d.trn.a.g(f,"Glyphs")||d.trn.a.g(f,"Canvas")||d.trn.a.g(f,"trn:Glyphs")){if(null!=c||"source-over"!==a){this.Ab();this.b.C();this.fa=!0;this.mc(c,a);return}this.Pa=!1;break}this.Pa&&this.b.C()}this.Pa&&this.Ab();this.fa=!1},Ab:function(){this.restore();this.pa()},Eb:function(a){a=this.b.D(a);d.trn.a.A(null!=a,
this.b.L()+": "+a+" is not defined");return parseFloat(a)},ya:function(a,e){a=this.b.D(a);return null!=a?parseFloat(a):e},s:function(a){a=this.b.D(a);d.trn.a.A(null!=a,this.b.L()+": "+a+" is not defined");return a},Ba:function(a,e){a=this.b.D(a);return null!=a?a:e},Ed:function(){var a;a=this.b.D("x:Key");d.trn.a.A(null!=a,"Key must be defined for elements in a resource dictionary");return a},Bc:function(){0===this.Sa&&this.b.mark();var a=!1,e=this.ya("Opacity",1);1>e&&(a||(a=!0,this.save(),this.Z()),
this.B(this.Ya(e)));e=this.b.D("RenderTransform");null!=e&&(a||(a=!0,this.save(),this.Z()),this.jf(e));e=this.b.D("Clip");null!=e&&(a||(this.save(),this.Z()),this.Yb(e),a=!0);return a},Yb:function(a){var e=!0;a&&"F"===a[0]&&(e=!1);this.ud(e?"evenodd":"nonzero");this.We(this.Ca(a));this.qd(a);this.m.push(d.trn.a.ke);this.o.push(e?["evenodd"]:[])},ff:function(a){var e=[];for(a=l.ob.getEnumerator(a.split(";"));a.Ld();){var c=a.current,b=new d.trn.Da,c=c.split(",");if(1<=c.length){if(0<c[0].length){var g=
c[0].split(")");if(2<=g.length){var h=g[0].substr(1).split(":");b.Sb=parseInt(h[0]);b.uc=parseInt(h[1])}b.Vb=parseInt(g[g.length-1]);b.yb=!0}2<=c.length&&(0<c[1].length&&(b.tc=parseFloat(c[1]),b.xc=!0),3<=c.length&&(0<c[2].length&&(b.Wb=parseFloat(c[2])),4<=c.length&&0<c[3].length&&(b.Xb=parseFloat(c[3]))))}e.add(b)}return e},Ve:function(){var a=this.s("UnicodeString"),e="",c=0,b,g,h;for(2<=a.length&&"{"===a.charAt(0)&&"}"===a.charAt(1)&&(a=a.substr(2));c<a.length;)b=a.charCodeAt(c),9==b?(e+=String.fromCharCode(10),
c++):128>b?(e+=String.fromCharCode(b),c++):191<b?224>b?(g=a.charCodeAt(c+1),e+=String.fromCharCode((b&31)<<6|g&63),c+=2):240>b?(g=a.charCodeAt(c+1),h=a.charCodeAt(c+2),e+=String.fromCharCode((b&15)<<12|(g&63)<<6|h&63),c+=3):(g=a.charCodeAt(c+1),h=a.charCodeAt(c+2),c4=a.charCodeAt(c+3),e+=String.fromCodePoint((b&7)<<18|(g&63)<<12|(h&63)<<6|c4&63),c+=4):console.warn("Invalid UTF-8 character");return e},nc:function(){var a=new d.trn.ea,b=this.b.D("Clip");null!=b&&(a=this.Ca(b));return a},pc:function(a,
b){return this.Ye&&1===a.length?b?d.trn.a.re:d.trn.a.se:b?d.trn.a.qe:d.trn.a.pe},Mc:function(a){return 0===Object.keys(a).length&&a.constructor===Object},pd:function(a){var e=this.Ba("trn:BlendMode","source-over"),e=this.fa?"source-over":e,c="source-over"!=e&&!this.Qb,f=this.Bc();this.Qb&&this.td(e);var g=this.Eb("OriginX"),h=this.Eb("OriginY"),k=this.s("FontUri");this.vb[k]=null;var m=this.Eb("FontRenderingEmSize"),n=this.ff(this.Ba("Indices",""));if(200>m){m/=200;f||(this.Z(),this.save(),f=!0);
var p=new d.trn.G;p.sb(m,0,0,m,g,h);m=200;h=0;this.m.push(d.trn.a.qb);this.o.push(p.rb())}p=0;g=new b;++this.Ze;var q=this.Ve(),x=0,w=0,r=m/100,A="";g.H(d.trn.a.He,0);for(var H={},E,z=0;z<n.length;++z){var y=n[z];if(x!==y.Wb||w!==y.Xb)A&&(g.H(this.pc(E,a),[A,x?x*r:0,h-w*r]),g.H(d.trn.a.Wc,[A])),x=y.Wb,w=y.Xb,A="";y.yb&&(H[A.length]=q.substr(p,y.Sb));y.xc?(this.Mc(H)||g.H(d.trn.a.Zc,[H]),E=A+(y.yb?String.fromCharCode(y.Vb+57344):q.substr(p,1)),g.H(this.pc(E,a),[E,x?x*r:0,h-w*r]),A&&g.H(d.trn.a.Wc,
[A]),g.H(d.trn.a.he,[y.tc*r]),H={},A=""):A+=y.yb?String.fromCharCode(y.Vb+57344):q.substr(p,1);z+=y.uc-1;p+=y.Sb}if(A||p<q.length)this.Mc(H)||g.H(d.trn.a.Zc,[H]),E=A+q.substr(p,q.length-p),g.H(this.pc(E,a),[E,0,0]);n=h=null;p=this.b.D("Fill");E=!1;null!=p&&(this.sc(p)?h=this.Oa(p,d.trn.a.ma,g):(E=!0,h=this.Pb(p,d.trn.a.ma,g)));p=this.b.D("OpacityMask");null!=p&&(console.warn("Uh oh OpacityMask Resource!"),n=this.Oa(p));if(!this.b.R()&&!a){for(this.b.F();this.b.advance();)a=this.b.L(),d.trn.a.g(a,
"Glyphs.Clip")?(d.trn.a.A(!this.b.R(),"Canvas.Clip: Must contain PathGeometry element"),this.b.F(),this.b.advance()&&(f||(f=!0,this.save(),this.Z()),p=new d.trn.G,p.aa(this.s("Transform")),this.m.push(d.trn.a.qb),this.o.push(p.rb()),d.trn.a.A(d.trn.a.g(this.b.L(),"PathGeometry"),"Path.Clip must contain PathGeometry"),a=this.s("Figures"),this.Yb(a),p=p.tb(),this.m.push(d.trn.a.qb),this.o.push(p.rb())),this.b.C()):d.trn.a.g(a,"Glyphs.Fill")?(this.b.F(),this.b.advance(),h=this.Za(d.trn.a.ma,g),this.b.C()):
d.trn.a.g(a,"Glyphs.OpacityMask")&&!this.fa&&(this.b.F(),this.b.advance(),n=this.Za(d.trn.a.ma,new b(d.trn.a.Mb)),this.b.C());this.b.C()}if(null==n||c)"otf"===k.substr(k.indexOf(".")+1)?(k=k.substr(0,k.length-4),k=parseInt(k.substr(7))):k=parseInt(k.substr(35,8),16),k="f"+k,Object.Id(this.Qa,k)?10>this.Qa[k].length&&(this.Qa[k]+=q.substr(0,10-this.Qa[k].length)):this.Qa[k]=q.substr(0,10),this.mf(d.trn.a.Ad(m)+"px "+k),null!==h&&(E||(h=new b(d.trn.a.ma,"#000000"),h.B(g)),this.Cc(h,g));f&&(this.restore(),
this.pa());if(null!=n||c)this.fa=!0,this.mc(n,e);this.fa=!1},dd:function(){var a=[];this.b.F();d.trn.a.A(this.b.advance(),"Gradient brushes must contain GradientStops");for(this.b.F();this.b.advance();){var b=this.s("Color"),c=this.s("Offset");a.push(c);a.push(this.cd(b))}this.b.C();this.b.C();return a},Qe:function(a,e,c){var f=this.b.D("Transform"),g=new b;g.save();this.Z();null!=f&&(c.aa(f),g.B(this.Y(c)));c=this.ya("Opacity",1);1>c&&g.B(this.Ya(c));f=this.s("StartPoint").split(",");c=parseFloat(f[0]);
var f=parseFloat(f[1]),h=this.s("EndPoint").split(",");c={type:d.trn.a.Ae,x0:c,y0:f,x1:parseFloat(h[0]),y1:parseFloat(h[1]),stops:this.dd()};g.H(a,[c]);g.B(e);g.restore();this.pa();return g},Se:function(a,e,c){var f=this.b.D("Transform"),g=new b,h=this.s("RadiusX"),k=this.s("RadiusY"),m=this.s("GradientOrigin"),n=this.s("Center");g.save();this.Z();var p=parseFloat(h),q=parseFloat(k);d.trn.a.A(0<p&&0<q,"Invalid radius value");var x=n.split(","),n=parseFloat(x[0]),x=parseFloat(x[1]),w=m.split(","),
m=parseFloat(w[0]),w=parseFloat(w[1]);if(null!=f||h!==k)null!=f&&c.aa(f),f=q/p,w/=f,x/=f,k=new d.trn.G,k.sb(1,0,0,f,0,0),c.Ma(k),g.B(this.Y(c));c=this.ya("Opacity",1);1>c&&g.B(this.Ya(c));h={type:d.trn.a.De,x0:m,y0:w,x1:n,y1:x,r:h,stops:this.dd()};g.H(a,[h]);g.B(e);g.restore();this.pa();return g},sf:function(){d.trn.a.A(!this.Ub,"Incorrect custom glyph start");this.m.push(d.trn.a.me);this.o.push(null);this.Ub=!0},Ke:function(){d.trn.a.A(this.Ub,"Incorrect custom glyph end");this.m.push(d.trn.a.ne);
this.o.push(null);this.Ub=!1},B:b.prototype.B,H:b.prototype.H,rf:function(a){var b=this.M.peek();a.Ga(b.ib)?this.H(d.trn.a.Nb,null):(a.m[0]===d.trn.a.pb&&(b.ib=a),this.B(a))},Cc:function(a,b){var c=this.M.peek();a.Ga(c.bb)?this.B(b):(a.m[0]===d.trn.a.ma&&(c.bb=a),this.B(a))},td:function(a){var b=this.M.peek();a!==b.xb&&(b.xb=a,this.H(d.trn.a.ve,[a]))},Ya:function(a){var e=this.M.peek();e.Ra*=a;return new b(d.trn.a.ue,[e.Ra])},ud:function(a){var b=this.M.peek();a!==b.ab&&(b.ab=a)},vd:function(a){var b=
this.M.peek();a!==b.gb&&(b.gb=a,this.m.push(d.trn.a.ze),this.o.push([a,this.$a().kb()]))},nf:function(a){var b=this.M.peek();a!==b.eb&&(b.eb=a,this.m.push(d.trn.a.xe),this.o.push([a]))},pf:function(a){var b=this.M.peek();a!==b.fb&&(b.fb=a,this.m.push(d.trn.a.ye),this.o.push([a]))},qf:function(a){var b=this.M.peek();a!==b.hb&&(b.hb=a,this.m.push(d.trn.a.Be),this.o.push([a]))},mf:function(a){var b=this.M.peek();a!==b.cb&&(b.cb=a,this.m.push(d.trn.a.te),this.o.push([a]))},Y:function(a){this.M.peek().wa.Ma(a);
return new b(d.trn.a.qb,a.rb())},$a:function(){return this.M.peek().wa},Le:function(){return this.M.peek().qa},We:function(a){this.M.peek().qa.lb(a)},Z:function(a){a=a?this.M.peek().Df():this.M.peek().clone();this.M.push(a);this.ga.add({})},pa:function(){this.M.pop();for(var a=Object.keys(this.ga[this.ga.length-1]),b=0;b<a;++b)this.H(d.trn.a.oe);this.ga.removeAt(this.ga.length-1)},Ne:function(a,e,c){var f=new b,g=this.b.D("Transform");f.save();this.Z();var h=this.s("Viewbox"),k=new d.trn.ea;k.Ta(h);
var h=this.s("Viewport"),m=new d.trn.ea;m.Ta(h);if(null!=g||k!==m){var h=m.v/k.v,n=m.u/k.u,p=m.j-k.j*h,k=m.l-k.l*n;null!=g&&c.aa(g);g=new d.trn.G;g.sb(h,0,0,n,p,k);c.Ma(g);f.B(this.Y(c))}c=this.ya("Opacity",1);1>c&&f.B(this.Ya(c));c=this.Ba("TileMode","None");g=this.s("ImageSource");this.vb[g]=null;f.H(a,[{type:d.trn.a.we,name:"i"+parseInt(g.split("/")[2]),tm:"None"===c?"no-repeat":"repeat"}]);f.B(e);f.restore();this.pa();return f},Oe:function(){var a=new b,e=this.b.D("Transform");a.save();this.Z();
var c=this.s("Viewbox"),f=new d.trn.ea;f.Ta(c);var c=this.s("Viewport"),g=new d.trn.ea;g.Ta(c);if(null!=e||f!==g){var c=g.v/f.v,h=g.u/f.u,k=g.j-f.j*c,f=g.l-f.l*h,g=new d.trn.G;null!=e&&g.aa(e);e=new d.trn.G;e.sb(c,0,0,h,k,f);g.Ma(e);a.B(this.Y(g))}e=this.ya("Opacity",1);1>e&&a.B(this.Ya(e));this.Ba("TileMode","None");e=this.s("ImageSource");this.vb[e]=null;e="i"+parseInt(e.split("/")[2]);this.gd?a.H(d.trn.a.Uc,[e,this.$a().kb()]):a.H(d.trn.a.Uc,[e]);a.restore();this.pa();return a},jf:function(a){if(null!=
a){var b=new d.trn.G;b.aa(a);this.B(this.Y(b))}},i:function(a){for(var b=itr_index=a.K,c=a.ha,f=c[itr_index];" "!==f&&","!==f;)++itr_index,f=c[itr_index];b=c.substring(b,itr_index);++itr_index;a.K=itr_index;return parseFloat(b)},Ca:function(a){var b=" ",c=new d.trn.Lb(a,0,null,0),f=new d.trn.ea,g=!0;f.Bb(0,0,0,0);if(c.K<c.ha.length)for(;" "===c.ha.charAt(c.K);)c.K++;for(;c.K<a.length;){if("A"<=c.ha.charAt(c.K)&&"Z">=c.ha.charAt(c.K)||"a"<=c.ha.charAt(c.K)&&"z">=c.ha.charAt(c.K))b=c.ha.charAt(c.K),
c.K++;else{var h,k;"a">b&&("H"!==b&&(c.f=0),"V"!==b&&(c.c=0));switch(b){case "m":case "M":c.c+=this.i(c);c.f+=this.i(c);g?(f.Bb(c.c,c.f,c.c,c.f),g=!1):f.ia(c.c,c.f);c.P=!1;break;case "l":case "L":c.c+=this.i(c);c.f+=this.i(c);f.ia(c.c,c.f);c.P=!1;break;case "c":case "C":h=this.i(c)+c.c;k=this.i(c)+c.f;f.ia(h,k);c.P=!0;c.na=this.i(c)+c.c;c.oa=this.i(c)+c.f;f.ia(c.na,c.oa);c.c+=this.i(c);c.f+=this.i(c);f.ia(c.c,c.f);break;case "q":case "Q":h=this.i(c)+c.c;k=this.i(c)+c.f;f.ia(h,k);c.c+=this.i(c);c.f+=
this.i(c);f.ia(c.c,c.f);c.P=!1;break;case "s":case "S":c.P||(c.na=c.c,c.oa=c.f);h=2*c.c-c.na;k=2*c.f-c.oa;f.ia(h,k);c.P=!0;c.na=this.i(c)+c.c;c.oa=this.i(c)+c.f;f.ia(c.na,c.oa);c.c+=this.i(c);c.f+=this.i(c);f.ia(c.c,c.f);break;case "h":case "H":c.c+=this.i(c);f.ia(c.c,c.f);c.P=!1;break;case "v":case "V":c.f+=this.i(c);f.ia(c.c,c.f);c.P=!1;break;default:this.i(c),c.P=!1}}for(;" "===a.charAt(c.K);)++c.K}return f.zf(this.$a())},oc:function(){var a=null;this.Z();var b=this.b.D("RenderTransform");if(null!=
b){var c=new d.trn.G;c.aa(b);this.Y(c)}var f=this.b.D("Stroke"),g=this.ya("StrokeThickness",1),b=this.b.D("Clip");null!=b&&(a=this.Ca(b));b=this.b.D("Data");if(!this.b.R()){for(this.b.F();this.b.advance();)if(c=this.b.L(),d.trn.a.g(c,"Path.Data")&&!this.b.R()){this.b.F();this.b.advance()&&(c=new d.trn.G,c.aa(this.s("Transform")),this.Y(c),d.trn.a.A(d.trn.a.g(this.b.L(),"PathGeometry"),"Path.Data must contain PathGeometry"),b=this.s("Figures"));this.b.C();break}else d.trn.a.g(c,"Path.Clip")?(d.trn.a.A(!this.b.R(),
"Path.Clip: Must contain PathGeometry element"),this.b.F(),this.b.advance()&&(c=new d.trn.G,c.aa(this.s("Transform")),this.Y(c),a=this.Ca(this.s("Figures")),c=c.tb(),this.Y(c)),this.b.C()):d.trn.a.g(c,"Path.Stroke")&&(f=!0);this.b.C()}null!=a?a.lb(this.Ca(b)):a=this.Ca(b);this.pa();f&&a.Gd(g);return a},ub:function(a,b,c){a.P=!1;if(null==a.ra)this.m.push(d.trn.a.Vc),this.o.push([a.c,a.f]);else for(var f=a.ra.length,g=a.c-b,h=a.f-c,k=h/g,m=Math.sqrt(g*g+h*h);1E-10<m;){var n=a.ra[a.Tb%f]-a.wb,p=n>m;
p&&(a.wb+=m,n=m);if(g){var q=Math.sqrt(n*n/(1+k*k));0>g&&(q=-q);b+=q;c+=k*q}else c+=0<h?n:-n;this.m.push(a.Tb%2?d.trn.a.Xc:d.trn.a.Vc);this.o.push([b,c]);m-=n;p||(++a.Tb,a.wb=0)}},Tc:function(a,b,c,f,g){a.P=!0;if(null==a.ra)this.m.push(d.trn.a.je),this.o.push([f,g,a.na,a.oa,a.c,a.f]);else{var h=this.$a().kb(),h=(Math.abs(a.c-b)+Math.abs(a.f-c))/5*h,k=a.c,m=a.f;a.c=b;a.f=c;for(var h=1/parseInt(h),n=0;1>=n;n+=h){var p=1-n,q=a.c,x=a.f;a.c=p*p*p*b+3*p*p*n*f+3*p*n*n*a.na+n*n*n*k;a.f=p*p*p*c+3*p*p*n*g+
3*p*n*n*a.oa+n*n*n*m;this.ub(a,q,x)}}},fe:function(a){if(null==a.ra)this.m.push(d.trn.a.le),this.o.push(null);else{var b=a.c,c=a.f;a.c=a.jd;a.f=a.kd;this.ub(a,b,c)}},df:function(a){a.jd=a.c;a.kd=a.f;this.m.push(d.trn.a.Xc);this.o.push([a.c,a.f]);a.P=!1;a.Tb=a.wc;a.wb=a.Ea},hf:function(a,b){var c,f,g=a.c,h=a.f;"a">b&&("H"!==b&&(a.f=0),"V"!==b&&(a.c=0));switch(b){case "m":case "M":a.c+=this.i(a);a.f+=this.i(a);this.df(a);break;case "l":case "L":a.c+=this.i(a);a.f+=this.i(a);this.ub(a,g,h);break;case "c":case "C":c=
this.i(a)+a.c;f=this.i(a)+a.f;a.na=this.i(a)+a.c;a.oa=this.i(a)+a.f;a.c+=this.i(a);a.f+=this.i(a);this.Tc(a,g,h,c,f);break;case "q":case "Q":c=this.i(a)+a.c;f=this.i(a)+a.f;a.c+=this.i(a);a.f+=this.i(a);this.H(d.trn.a.Ce,[c,f,a.c,a.f]);a.P=!1;break;case "s":case "S":a.P||(a.na=a.c,a.oa=a.f);c=2*a.c-a.na;f=2*a.f-a.oa;a.P=!0;a.na=this.i(a)+a.c;a.oa=this.i(a)+a.f;a.c+=this.i(a);a.f+=this.i(a);this.Tc(a,g,h,c,f);break;case "h":case "H":a.c+=this.i(a);this.ub(a,g,h);a.P=!1;break;case "v":case "V":a.f+=
this.i(a);this.ub(a,g,h);a.P=!1;break;default:this.i(a),a.P=!1}},Pe:function(a){if("Flat"===a)return"butt";if("Square"===a)return"square";if("Round"===a||"Triangle"===a)return"round";d.trn.a.A(!1,"Invalid line cap "+a);return""},qd:function(a){this.rd(a,null,0)},rd:function(a,b,c){var f=" ";b=new d.trn.Lb(a,0,b,c);c=b.ha.charAt(b.K);this.m.push(d.trn.a.ie);this.o.push(null);if(b.K<b.ha.length)for(;" "===c;)b.K++,c=b.ha.charAt(b.K);for(;b.K<a.length;)for("A"<=c&&"Z">=c||"a"<=c&&"z">=c?(f=c,"z"!==c&&
"Z"!==c||this.fe(b),b.K++):this.hf(b,f),c=b.ha.charAt(b.K);" "===c;)++b.K,c=b.ha.charAt(b.K)},save:b.prototype.save,restore:b.prototype.restore,Od:b.prototype.Od,kf:function(){var a=this.Ba("trn:BlendMode","source-over"),a=this.fa?"source-over":a,e="source-over"!=a&&!this.Qb,c=this.b.D("Data"),f=!0;c&&"F"===c[0]&&(f=!1);var g=new b(d.trn.a.Mb,f?["evenodd"]:null),h=!1,k=this.Bc(),m=null,n=this.b.D("Fill");null!=n&&(m=this.sc(n)?this.Oa(n,d.trn.a.ma,g):this.Pb(n,d.trn.a.ma,g));this.Qb&&this.td(a);var p=
n=null,q=this.ya("StrokeThickness",1),x=this.b.D("Stroke");null!=x&&(this.vd(q),n=this.sc(x)?this.Oa(x,d.trn.a.pb,new b(d.trn.a.Nb)):this.Pb(x,d.trn.a.pb,new b(d.trn.a.Nb)));var x=null,w=this.b.D("OpacityMask");null!=w&&(console.warn("Uh oh OpacityMask Resource!"),x=this.Oa(w));w=null;if(!this.b.R()){for(this.b.F();this.b.advance();){var r=this.b.L();d.trn.a.g(r,"Path.Clip")?(d.trn.a.A(!this.b.R(),"Path.Clip: Must contain PathGeometry element"),this.b.F(),this.b.advance()&&(k||(k=!0,this.save(),this.Z()),
w=new d.trn.G,w.aa(this.s("Transform")),this.B(this.Y(w)),d.trn.a.A(d.trn.a.g(this.b.L(),"PathGeometry"),"Path.Clip must contain PathGeometry"),r=this.s("Figures"),this.Yb(r),w=w.tb()),this.b.C()):d.trn.a.g(r,"Path.Data")&&!this.b.R()?(this.b.F(),this.b.advance()&&(c=new d.trn.G,c.aa(this.s("Transform")),null!=w?w.Ma(c):w=c,this.B(this.Y(w)),d.trn.a.A(d.trn.a.g(this.b.L(),"PathGeometry"),"Path.Data must contain PathGeometry"),c=this.s("Figures")),this.b.C()):d.trn.a.g(r,"Path.Fill")?(this.b.F(),this.b.advance(),
null!=x||e||"ImageBrush"!==this.b.L()?m=this.Za(d.trn.a.ma,g):(h=!0,this.B(this.Oe())),this.b.C()):d.trn.a.g(r,"Path.OpacityMask")?this.fa||(this.b.F(),this.b.advance(),x=this.Za(d.trn.a.ma,g),this.b.C()):d.trn.a.g(r,"Path.Stroke")&&(this.b.F(),this.b.advance(),n=this.Za(d.trn.a.pb,new b(d.trn.a.Nb),q),this.b.C())}this.b.C()}if(null==x&&!e&&!h){d.trn.a.A(null!=c,"Paths must have Data defined");h=this.b.D("StrokeDashArray");if(null!=h)for(h=h.split(" "),p=Array(h.length),w=0;w<h.length;++w)if(p[w]=
parseFloat(h[w])*q,!p[w]||.02>p[w])p[w]=.02;this.ud(f?"evenodd":"nonzero");f=this.ya("StrokeDashOffset",0);null!=p&&null!=m&&(this.qd(c),null!=m&&this.Cc(m,g),m=null);this.rd(c,p,f);null!=m&&this.Cc(m,g);null!=n&&(this.nf(this.Pe(this.Ba("StrokeStartLineCap","Flat"))),this.pf(this.Ba("StrokeLineJoin","miter").toLowerCase()),this.qf(this.ya("StrokeMiterLimit",10)),this.rf(n))}k&&(this.restore(),this.pa());if(null!=x||e)this.fa=!0,this.mc(x,a);this.fa=!1},cd:function(a){var b=1,c=[255,255,255,255];
if("#"===a.charAt(0)){if(7===a.length)return a;var f,g;d.trn.a.A(9===a.length,"Color "+a+" is invalid in a XOD file");b=a.substr(1,2);f=a.substr(3,2);g=a.substr(5,2);a=a.substr(7,2);b=parseInt(b,16)/255;c[0]=parseInt(f,16);c[1]=parseInt(g,16);c[2]=parseInt(a,16)}else"s"===a.charAt(0)?(f=a.split("#")[1].split(","),3<f.length?(b=parseFloat(f[0]),g=255*parseFloat(f[1]),c[0]=parseInt(0>g?0:255<g?255:g),g=255*parseFloat(f[2]),c[1]=parseInt(0>g?0:255<g?255:g),g=255*parseFloat(f[3])):(g=255*parseFloat(f[0]),
c[0]=parseInt(0>g?0:255<g?255:g),g=255*parseFloat(f[1]),c[1]=parseInt(0>g?0:255<g?255:g),g=255*parseFloat(f[2])),c[2]=parseInt(0>g?0:255<g?255:g)):d.trn.a.A(!1,"Invalid color for a XOD file");return"rgba("+c[0]+","+c[1]+","+c[2]+","+d.trn.a.Ad(b)+")"},Te:function(a,b){return this.Pb(this.s("Color"),a,b)},Pb:function(a,e,c){a=new b(e,this.cd(a));a.B(c);return a},qc:function(){var a=this.Sa,b=this.m,c=this.o;this.m=[];this.o=[];this.Sa=this.b.depth;this.Z(!0);if(!this.b.R()||!d.trn.a.g(this.b.L(),"Canvas"))for(this.Pa=
!1;this.yc(););this.pa();var f={operators:this.m,data:this.o};this.Sa=a;this.m=b;this.o=c;return f},ed:function(a,e,c,f){var g=new b,h=this.s("Viewbox"),k=new d.trn.ea;k.Ta(h);var h=this.s("Viewport"),m=new d.trn.ea;m.Ta(h);h=this.b.D("Transform");g.save();this.Z();var n;if(!this.b.R()){for(this.b.F();this.b.advance();){var p=this.b.L();d.trn.a.g(p,"VisualBrush.Visual")&&(this.b.F(),d.trn.a.A(this.b.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element"),this.Z(!0),this.M.peek().wa=
new d.trn.G,n=this.Ob(),this.pa(),this.b.C())}this.b.C()}if("undefined"!==typeof n&&0!==n.u&&0!==n.v){var p=m.j-k.j,q=m.l-k.l;k.lb(n);m=k;m.j+=p;m.l+=q}if(0===k.v||0===k.u)return g=new b(a,"rgba(0,0,0,0)"),g.B(e),g;if(null!=h||k!==m)p=m.v/k.v,n=m.u/k.u,q=m.j-k.j*p,m=m.l-k.l*n,null!=h&&c.aa(h),h=new d.trn.G,h.sb(p,0,0,n,q,m),c.Ma(h),g.B(this.Y(c));m=this.$a().kb();h=Math.min(k.v,k.u);p=this.ya("Opacity",1);1>p&&g.B(this.Ya(p));n=this.Ba("TileMode","None");q={};p=this.b.D("Visual");null!=p&&(p=this.Oa(p),
q.operators={operators:p.m,data:p.o});if(!this.b.R()){for(this.b.F();this.b.advance();)p=this.b.L(),d.trn.a.g(p,"VisualBrush.Visual")&&(this.b.F(),d.trn.a.A(this.b.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element"),q.operators=this.qc(),this.b.C());this.b.C()}q.type=d.trn.a.Ie;q.tm="None"===n?"no-repeat":"repeat";a===d.trn.a.pb&&(q.strokeAdjust=f/c.kb());if(k.j||k.l)q.x=k.j,q.y=k.l;q.w=k.v;q.h=k.u;q.minwh=h;q.scale=m;g.H(a,[q]);g.B(e);g.restore();this.pa();return g},sc:function(a){return"{"===
a.charAt(0)},Oa:function(a){var e=a.indexOf("StaticResource");d.trn.a.A(0<e,"Invalid resource reference: "+a);e+=15;a=a.substr(e,a.length-1-e);for(var e=null,c=this.ga.length-1;0<=c;--c)if(Object.Id(this.ga[c],a)){e=this.ga[c][a];break}d.trn.a.A(null!=e,"Dictionary key "+a+" does not exist.");return new b(d.trn.a.Ee,[a])},yc:function(){var a;if(this.Pa){if(this.b.depth===this.Sa)return d.trn.a.g(this.b.L(),"Canvas")&&this.Ab(),!1;a=this.b.advance();if(!a){this.b.C();if(this.Rb.peek()===this.b.depth)return this.Rb.pop(),
this.Ke(),!0;if(this.b.depth===this.Sa)return d.trn.a.g(this.b.L(),"Canvas")&&this.Ab(),!1;this.Ab();return!0}}this.Pa=!0;a=this.b.L();d.trn.a.g(a,"Canvas")?this.gf():d.trn.a.g(a,"Path")?this.kf():d.trn.a.g(a,"Glyphs")?this.pd(!1):d.trn.a.g(a,"trn:Glyphs")&&(this.b.R()||this.Rb.push(this.b.depth),this.pd(!0),this.b.R()||(this.b.F(),this.sf()));return!0},de:function(){var a=d.trn.a.ma,e=new b(d.trn.a.Mb),a=this.ed(a,e,new d.trn.G),e=this.Ed();++this.vc;this.ga[this.ga.length-1][e]=a;this.H(d.trn.a.Yc,
[e,a.m,a.o])},ce:function(a){a=this.qc();var b=this.Ed();++this.vc;this.ga[this.ga.length-1][b]=a;this.H(d.trn.a.Yc,[b,a.operators,a.data])},Za:function(a,b,c){var f=new d.trn.G,g=this.b.L(),h;d.trn.a.g(g,"VisualBrush")?h=this.ed(a,b,f,c):(d.trn.a.g(g,"ImageBrush")?h=this.Ne(a,b,f):d.trn.a.g(g,"LinearGradientBrush")?h=this.Qe(a,b,f):d.trn.a.g(g,"RadialGradientBrush")?h=this.Se(a,b,f):d.trn.a.g(g,"SolidColorBrush")?h=this.Te(a,b):d.trn.a.A(!1,"Invalid Brush Type: "+g),"undefined"!==typeof c&&this.vd(c/
f.kb()));return h},sd:function(){var a=this.b.L();if(d.trn.a.g(a,"ResourceDictionary")&&!this.b.R()){for(this.b.F();this.b.advance();)a=this.b.L(),d.trn.a.g(a,"VisualBrush")?this.de():d.trn.a.g(a,"Canvas")?this.ce():d.trn.a.A(!1,"Resource type is invalid: "+a);this.b.C()}},Me:function(){for(var a="";!this.done;)a+=this.Db();return a},Db:function(){this.nd=!1;for(this.vb={};this.m.length<this.hd&&!this.nd&&this.yc(););this.yc()||(this.done=!0);var a={operators:this.m,data:this.o};this.m=[];this.o=
[];return a},wf:function(){var a=[],b=this.vb,c;for(c in b)a.add(c.substr(1));return a},done:!1,Pa:!1,fa:!1,md:0,ld:0,vc:0,bf:0,gd:!1,Ze:0,hd:0,Qa:null,vb:null,Sa:0,ga:null,M:null,b:null,Rb:null,Ub:!1};d.trn.Da=function(){this.xc=this.yb=!1;this.Sb=this.uc=1;this.tc=this.Wb=this.Xb=this.Vb=0};d.trn.Da.prototype={yb:!1,xc:!1,Sb:0,uc:0,Vb:0,tc:0,Wb:0,Xb:0};d.trn.Na=function(){};d.trn.Na.Bf=function(a,b){var c=new d.trn.Na;c.ib="black";c.bb="black";c.ab="nonzero";c.Ra=1;c.xb="source-over";c.gb=1;c.eb=
"butt";c.fb="miter";c.hb=10;c.cb="10px sans-serif";c.wa=new d.trn.G;c.qa=new d.trn.ea;c.qa.Bb(0,0,a,b);return c};d.trn.Na.prototype={clone:function(){var a=new d.trn.Na;a.ib=this.ib;a.bb=this.bb;a.ab=this.ab;a.Ra=this.Ra;a.xb=this.xb;a.gb=this.gb;a.eb=this.eb;a.fb=this.fb;a.hb=this.hb;a.cb=this.cb;a.wa=new d.trn.G;a.wa.rc(this.wa);a.qa=new d.trn.ea;a.qa.Bb(this.qa.j,this.qa.l,this.qa.v,this.qa.u);return a},Df:function(){var a=new d.trn.Na;a.ib="black";a.bb="black";a.ab="nonzero";a.Ra=1;a.xb="source-over";
a.gb=1;a.eb="butt";a.fb="miter";a.hb=10;a.cb="10px sans-serif";a.wa=new d.trn.G;a.wa.rc(this.wa);a.qa=new d.trn.ea;return a},ib:null,bb:null,ab:null,Ra:0,gb:0,eb:null,fb:null,hb:0,cb:null,wa:null,qa:null};d.trn.Wa=function(a,b){this.x=a;this.y=b};d.trn.Wa.prototype={x:0,y:0};d.trn.ea=function(){this.l=this.j=-1E6;this.v=this.u=2E6};d.trn.ea.prototype={Bb:function(a,b,c,f){this.j=a;this.l=b;this.v=c;this.u=f},Cf:function(){return 0<this.v&&0<this.u},Ta:function(a){a=a.split(",");d.trn.a.A(4===a.length,
"Rectangles should contain 4 numbers");this.j=parseFloat(a[0]);this.l=parseFloat(a[1]);this.v=parseFloat(a[2]);this.u=parseFloat(a[3])},zf:function(a){if(a.fd())return this;var b=new d.trn.Wa(this.j,this.l),c=new d.trn.Wa(this.j,this.l+this.u),f=new d.trn.Wa(this.j+this.v,this.l),g=new d.trn.Wa(this.j+this.v,this.l+this.u);a.ac(b);a.ac(c);a.ac(f);a.ac(g);a=Math.min(b.x,c.x,f.x,g.x);var h=Math.min(b.y,c.y,f.y,g.y),k=new d.trn.ea;k.Bb(a,h,Math.max(b.x,c.x,f.x,g.x)-a,Math.max(b.y,c.y,f.y,g.y)-h);return k},
ia:function(a,b){a<this.j?(this.v+=this.j-a,this.j=a):a>this.j+this.v&&(this.v=a-this.j);b<this.l?(this.u+=this.l-b,this.l=b):b>this.l+this.u&&(this.u=b-this.l)},Fc:function(a){this.ia(a.j,a.l);this.ia(a.j+a.v,a.l+a.u)},lb:function(a){var b,c,f,g,h,k,m;b=this.j;c=this.j+this.v;f=this.l;g=this.l+this.u;h=a.j;k=a.j+a.v;m=a.l;a=a.l+a.u;c<h||k<b||g<m||a<f?this.j=this.v=this.l=this.u=0:(this.j=b<h?h:b,this.v=(c<k?c:k)-this.j,this.l=f<m?m:f,this.u=(g<a?g:a)-this.l,this.v&&this.u||(this.j=this.v=this.l=
this.u=0))},Gd:function(a){this.j-=a;this.l-=a;this.v+=2*a;this.u+=2*a},j:0,l:0,v:0,u:0};d.trn.G=function(){};d.trn.G.prototype={T:1,U:0,V:0,W:1,ba:0,ca:0,aa:function(a){var b=[1,0,0,1,0,0];a=a.split(",");for(var c=0;c<a.length&&6>c;++c)b[c]=parseFloat(a[c]);this.T=b[0];this.U=b[1];this.V=b[2];this.W=b[3];this.ba=b[4];this.ca=b[5]},sb:function(a,b,c,f,g,h){this.T=a;this.U=b;this.V=c;this.W=f;this.ba=g;this.ca=h},rc:function(a){this.T=a.T;this.U=a.U;this.V=a.V;this.W=a.W;this.ba=a.ba;this.ca=a.ca},
Ma:function(a){var b=this.T,c=this.U,f=this.V,g=this.W;this.T=a.T*b+a.U*f;this.U=a.T*c+a.U*g;this.V=a.V*b+a.W*f;this.W=a.V*c+a.W*g;this.ba=a.ba*b+a.ca*f+this.ba;this.ca=a.ba*c+a.ca*g+this.ca},tb:function(){var a=new d.trn.G,b=this.T*this.W-this.U*this.V;if(!b)return a;a.T=this.W/b;a.V=-this.V/b;a.ba=(this.V*this.ca-this.ba*this.W)/b;a.U=-this.U/b;a.W=this.T/b;a.ca=-(this.T*this.ca-this.ba*this.U)/b;return a},ac:function(a){var b=a.x*this.U+a.y*this.W+this.ca;a.x=a.x*this.T+a.y*this.V+this.ba;a.y=
b},kb:function(){var a=.707106781*this.T+.707106781*this.U,b=.707106781*this.V+.707106781*this.W;return Math.sqrt(a*a+b*b)},fd:function(){return 1!==this.T||this.U||this.V||1!==this.W||this.ba||this.ca?!1:!0},rb:function(){return this.Re()},Re:function(){return this.fd()?null:[this.T,this.U,this.V,this.W,this.ba,this.ca]}};d.trn.Lb=function(a,b,c,f){this.ha=a;this.K=b;this.c=this.f=0;this.P=!1;this.ra=c;if(null!=this.ra){for(b=a=0;b<this.ra.length;++b)a+=this.ra[b];this.Ea=f%a;0>this.Ea&&(this.Ea+=
a);for(b=this.wc=0;this.Ea>this.ra[b];++b)this.Ea-=this.ra[b],++this.wc}};d.trn.Lb.prototype={ha:null,K:0,ra:null,Tb:0,wb:0,wc:0,Ea:0,c:0,f:0,jd:0,kd:0,P:!1,na:0,oa:0};d.trn.od=function(a,b,c){this.af=a;this.cf=b;this.$e=c};d.trn.od.prototype={$e:0,cf:0,af:0};d.trn.a.$("myglobs.trn.Converter");d.trn.Da.$("myglobs.trn._index");d.trn.Na.$("myglobs.trn._gState");d.trn.Wa.$("myglobs.trn.Point");d.trn.ea.$("myglobs.trn._rect");d.trn.G.$("myglobs.trn._matrix2D");d.trn.Lb.$("myglobs.trn._abbrGeomItr");d.trn.od.$("myglobs.trn._pageInfo");
d.trn.a.dg="http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key";d.trn.a.jg="http://schemas.openxps.org/oxps/v1.0/resourcedictionary-key";d.trn.a.pg="http://schemas.microsoft.com/winfx/2006/xaml";d.trn.a.tf="http://schemas.microsoft.com/xps/2005/06";d.trn.a.qg="http://schemas.microsoft.com/winfx/2006/xaml/presentation";d.trn.a.kg="http://schemas.openxps.org/oxps/v1.0";d.trn.a.sg="http://schemas.microsoft.com/xps/2005/06/documentstructure";d.trn.a.ig="http://schemas.openxps.org/oxps/v1.0/documentstructure";
d.trn.a.ng="http://schemas.openxmlformats.org/package/2006/relationships";d.trn.a.Vf="http://schemas.openxmlformats.org/package/2006/content-types";d.trn.a.eg="http://schemas.openxmlformats.org/markup-compatibility/2006";d.trn.a.Wf="http://schemas.openxmlformats.org/package/2006/metadata/core-properties";d.trn.a.Xf="http://purl.org/dc/elements/1.1/";d.trn.a.Yf="http://purl.org/dc/terms/";d.trn.a.rg="http://www.w3.org/XML/1998/namespace";d.trn.a.og="clr-namespace:PDFTron.SilverDox.Internal;assembly=SilverDox";
d.trn.a.tg="http://schemas.microsoft.com/xps/2005/06/restricted-font";d.trn.a.lg="http://schemas.openxps.org/oxps/v1.0/restricted-font";d.trn.a.fg="application/vnd.ms-package.obfuscated-opentype";d.trn.a.mg="http://www.pdftron.com/silverdox/2010/09";d.trn.a.Ge=0;d.trn.a.Fe=1;d.trn.a.qb=2;d.trn.a.bg=3;d.trn.a.ze=4;d.trn.a.xe=5;d.trn.a.pb=6;d.trn.a.ma=7;d.trn.a.ue=8;d.trn.a.Yc=9;d.trn.a.oe=10;d.trn.a.he=11;d.trn.a.Ee=12;d.trn.a.ie=13;d.trn.a.le=14;d.trn.a.Mb=15;d.trn.a.Nb=16;d.trn.a.ke=17;d.trn.a.Xc=
18;d.trn.a.Vc=19;d.trn.a.Ce=20;d.trn.a.je=21;d.trn.a.te=22;d.trn.a.pe=23;d.trn.a.Wc=24;d.trn.a.He=25;d.trn.a.Be=26;d.trn.a.ye=27;d.trn.a.Uc=28;d.trn.a.ag=29;d.trn.a.$f=30;d.trn.a.se=31;d.trn.a.me=32;d.trn.a.ne=33;d.trn.a.ve=34;d.trn.a.Zc=35;d.trn.a.Je=36;d.trn.a.Zf=37;d.trn.a.qe=38;d.trn.a.re=39;d.trn.a.Ie=1;d.trn.a.Ae=2;d.trn.a.De=3;d.trn.a.we=4;d.trn.a.gg="S r t T w c s f a L R P A b z F X C M l q B n x m W i j I Z d D e xw cgb cge g bO tm".split(" ");d.trn.a.hg="S r t T w c s f a L R P A b z F X C M l q B n xc m W i j I Z d D e xcw cgb cge g bO tm".split(" ")})();self.trn.a||(self.trn=trn);function U(b){this.I="";this.Jf=new self.Xa.hc(b);V(this);this.start=0}U.prototype={xd:102400,mark:function(b){var a=b-this.start;a>U.prototype.xd&&(this.I=this.I.slice(a),this.start=b)},indexOf:function(b,a){var e;a-=this.start;do e=this.I.indexOf(b,a);while(-1===e&&V(this));return e+this.start},charAt:function(b){b-=this.start;b>=this.I.length&&V(this);return this.I.charAt(b)},substring:function(b,a){b-=this.start;a-=this.start;return this.I.substring(b,a)}};
function V(b){var a=b.Jf.Dd(U.prototype.xd);return a.length?(b.I+=a,!0):!1}self.Db=function(){if(self.jb.done)return self.postMessage({command:"done"}),self.jb=null,!1;var b=self.jb.Db();self.postMessage({command:"nextChunk",resources:self.jb.wf(),dataString:b});return!0};self.Xd=U;self.wd=!1;
self.onmessage=function(b){switch(b.data.command){case "data":b=new self.$d(new self.Xd(b.data.dataString));self.jb=new self.trn.a(b,self.wd,self.Hf);if(self.yd)for(;self.Db(););break;case "nextChunk":self.yd||self.jb&&self.Db();break;case "cancel":self.jb=null;self.postMessage({command:"done"});break;case "options":self.wd=b.data.imageScaling;self.Hf=b.data.specialBlendSupported;self.yd=b.data.continueWithoutPrompt;break;default:throw Error("Unknown message command "+b.data.command);}};
